### ISSUE TITLE
_init_error_handling() breaks Flask's handling of RequestRedirect when not in debug mode

### ISSUE THREAD

**Issue by twosigmajab** [plangrid/flask-rebar#24]
Out of the box, Flask sets up nice automatic handling of trailing slash redirects. So if you have a handler mapped to a URL like `/swagger/ui/` (such as the one Flask-Rebar sets up for you), but the user makes a request like `/swagger/ui` (note no trailing slash), then normally, Flask serves the user a redirect to `/swagger/ui/` without your having to do anything extra, *whether or not `app.debug` is True*.

However, Flask-Rebar's `_init_error_handling` is interfering with this in the case that `app.debug` is False. I hit this after writing a function `start_devserver(debug=False)`. Before calling `app.run(debug=debug)`, it prints out the string `f"* Swagger UI available at http://localhost:5000/{registry.prefix}/{registry.swagger_ui_path}"`. With `debug=False`, clicking the resulting link would result in a 500 error and the following stack trace:
```
[2018-10-26 15:57:55,690] ERROR in app: Exception on /swagger/ui [GET]
Traceback (most recent call last):
  File "/private/tmp/testvenv/lib/python3.7/site-packages/werkzeug/routing.py", line 1538, in match
    rv = rule.match(path, method)
  File "/private/tmp/testvenv/lib/python3.7/site-packages/werkzeug/routing.py", line 776, in match
    raise RequestSlash()
werkzeug.routing.RequestSlash

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/testvenv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/private/tmp/testvenv/lib/python3.7/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/private/tmp/testvenv/lib/python3.7/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/private/tmp/testvenv/lib/python3.7/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/private/tmp/testvenv/lib/python3.7/site-packages/werkzeug/routing.py", line 1542, in match
    safe='/:|+') + '/', query_args))
werkzeug.routing.RequestRedirect: 301 Moved Permanently: None
127.0.0.1 - - [26/Oct/2018 15:57:55] "GET /swagger/ui HTTP/1.1" 500 -
```

It looks like the logic here is the culprit:
https://github.com/plangrid/flask-rebar/blob/83aea998900832f47d33a0061052f78433cba720/flask_rebar/rebar.py#L586

It's some combination of:
1. catching too-broad an exception type (as warned against in https://github.com/pallets/flask/issues/2948#issuecomment-430867522)
1. clobbering (and/or forgetting to re-add) the special handling for `RequestRedirect` that is done in https://github.com/pallets/flask/blob/70b45094ab3d62b919a84f8fb8376e6614a98dd3/flask/app.py#L1771)
1. doing different things when `app.debug` is True or False for exceptions like `RequestRedirect` that should not care.

I also noticed that a nested function named `handle_werkzeug_http_error()` is defined twice inside `_init_error_handling()`, which seems like unintentional copy pasta.

**Comment by barakalon** [comment]
Fantastic writeup - thanks!

I've put up a potential fix with https://github.com/plangrid/flask-rebar/pull/25. The error handling is getting a little bit messy, but I think it's a reasonable fix.

I was having a bit of trouble routing `/swagger/ui` properly, omitting the need for the redirect. But its a bit tricky with blueprints, so I've punted on that fix for now.

> I also noticed that a nested function named handle_werkzeug_http_error() is defined twice

Good catch! I fixed that as well.

**Comment by juliusiv** [comment]
@twosigmajab this should be fixed with the latest version, `1.0.7`. Thanks for reporting and thanks @barakalon for fixing this!

**Comment by twosigmajab** [comment]
Thanks for getting a fix out so fast!

**Comment by twosigmajab** [comment]
I just tried hitting `http://localhost:5000/swagger/ui` in the most basic possible Flask-Rebar app run in development mode (see below) and am still getting the traceback for the `werkzeug.routing.RequestRedirect: 301 Moved Permanently: None` exception shown in the browser rather than actually getting redirected to http://localhost:5000/swagger/ui/ (with the trailing slash). Reproduced with the latest release (1.1.0) and on latest master. Should this be reopened?

```
$ cat app.py
from flask_rebar import Rebar
from flask import Flask

app = Flask(__name__)
rebar = Rebar()
registry = rebar.create_handler_registry()

@registry.handles('/foo')
def foo():
    return 'foo'

rebar.init_app(app)

$ env FLASK_ENV=development FLASK_APP=app:app flask run
...
127.0.0.1 - - [26/Nov/2018 14:35:13] "GET /swagger/ui HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/private/tmp/venv/lib/python3.7/site-packages/flask_rebar/rebar.py", line 614, in handle_request_redirect_error
    raise error
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/private/tmp/venv/lib/python3.7/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/private/tmp/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1542, in match
    safe='/:|+') + '/', query_args))
werkzeug.routing.RequestRedirect: 301 Moved Permanently: None
```

**Comment by twosigmajab** [comment]
Just chiming in to say this is still an issue that is biting the Flask-Rebar users I'm supporting, as mentioned in my previous comment. I'd reopen this but I don't seem to have permission, can someone please reopen?

**Comment by juliusiv** [comment]
Hmm, I'm looking at this now and I can reproduce the issue. If I comment out these lines https://github.com/plangrid/flask-rebar/blob/master/flask_rebar/rebar.py#L621-L623 the error doesn't throw anymore, which makes sense because that's literally what I commented out. However, if the intended behavior is that that error isn't thrown regardless of the debug mode, then it seems to me that I never want to re-throw the error.

**Comment by twosigmajab** [comment]
Thanks @juliusiv, I think that's right; I see no reason for this behavior in the debug case. My guess is that this is more copy pasta -- the `if current_app.debug` currently appears e.g. in the `handle_generic_error()` below, where it *is* intended. We found and fixed other copy pasta around this code earlier (see above), so this likely is too.
